# cloudbuild.yaml
options:
  logging: CLOUD_LOGGING_ONLY
  pool: {}
projectId: PROJECT_ID
steps:
  - name: gcr.io/k8s-skaffold/pack
    entrypoint: pack
    args:
      - build
      - REPOSITORY_URI
      - --builder
      - gcr.io/buildpacks/builder:latest
      - --network
      - cloudbuild